# Training configuration of BECTRA (https://arxiv.org/abs/2211.00792)

batch_type: folded
batch_size: 64
accum_grad: 4
max_epoch: 100
patience: none
init: none
best_model_criterion:
-   - valid
    - cer_transducer
    - min
keep_nbest_models: 10

model: bectra
model_conf:
    asr_weight: 0.3
    interctc_weight: 0.5
    aux_weight: 0.5
    lsm_weight: 0.1
    length_normalized_loss: false
    predec_drop_rate: 0.0
    embed_enc_layer: conv2d

freeze_param: [
    "bert.transformer"
]

encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 1024
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31
    interctc_layer_idx: [6]
    interctc_use_conditioning: false

predecoder: hugging_face_transformers
predecoder_conf:
    model_name_or_path: "bert-base-chinese"

decoder: transducer
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 256
    dropout: 0.1
    dropout_embed: 0.2

joint_net_conf:
    joint_space_size: 256

optim: adam
optim_conf:
    lr: 0.002
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000

num_att_plot: 0

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 5